---
apiVersion: v1
kind: ConfigMap
metadata:
  name: charon-config
  namespace: $NAMESPACE
data:
  CHARON_VALIDATOR_API_ADDRESS: "0.0.0.0:3600"
  CHARON_P2P_TCP_ADDRESS: "0.0.0.0:3610"
  CHARON_MONITORING_ADDRESS: "0.0.0.0:3620"
  CHARON_P2P_UDP_ADDRESS: "0.0.0.0:3630"
  CHARON_P2P_BOOTNODE_RELAY: "true"
  CHARON_P2P_BOOTNODES: "http://bootnode.lb.gcp.obol.tech:3640/enr"
  CHARON_BEACON_NODE_ENDPOINTS: $BEACON_NODE_ENDPOINTS
  CHARON_DATA_DIR: "/charon"
  CHARON_LOCK_FILE: "/charon/cluster-lock.json"
  CHARON_P2P_EXTERNAL_HOSTNAME: ""
  CHARON_LOG_LEVEL: "debug"
  CHARON_P2P_DISABLE_REUSEPORT: "true"
