{
 "title": "Single Charon Node Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Execution Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "GETH",
     "type": "stat",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "1" }
     ]
    },
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"geth\"}"
      }
     ]
    },
    {
     "title": "Peers",
     "type": "stat",
     "description": "Peers connected with our execution client. Also number of peers we dialled and we are serving.",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "p2p_peers", "legendFormat": "peers" }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "description": "Memory used by execution client.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "rate(system_memory_allocs[1m])", "legendFormat": "alloc" },
      { "expr": "system_memory_used", "legendFormat": "used" },
      { "expr": "system_memory_held", "legendFormat": "held" }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "system_cpu_sysload", "legendFormat": "system" },
      { "expr": "system_cpu_syswait", "legendFormat": "iowait" },
      { "expr": "system_cpu_procload", "legendFormat": "geth" }
     ]
    },
    {
     "title": "Latest Chain Header",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "chain_head_header" }
     ]
    }
   ]
  },
  {
   "title": "Beacon Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "LIGHTHOUSE",
     "type": "stat",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "1" }
     ]
    },
    {
     "title": "Syncing chain counts",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "sync_range_chains", "legendFormat": "{{range_type}}" }
     ]
    },
    {
     "title": "Current Slot",
     "type": "stat",
     "description": "Lighthouse's reported current slot (unsafe not finalised)",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "max(slotclock_present_slot)" }
     ]
    },
    {
     "title": "Peer Sync Status",
     "type": "piechart",
     "description": "The sync status for lighthouse's peers",
     "gridPos": { "h": 5, "w": 4, "x": 9, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sync_peers_per_status", "legendFormat": "{{sync_status}}" }
     ]
    },
    {
     "title": "Peer Type",
     "type": "piechart",
     "description": "Peers that have dialed us. Indicates if our node is reachable",
     "gridPos": { "h": 5, "w": 4, "x": 13, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "network_inbound_peers", "legendFormat": "Inbound" },
      { "expr": "network_outbound_peers", "legendFormat": "Outbound" }
     ]
    },
    {
     "title": "Eth1 Execution Client Connected",
     "type": "stat",
     "description": "Identifies if there is an upstream execution client connected",
     "gridPos": { "h": 4, "w": 4, "x": 17, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "sync_eth1_connected", "legendFormat": "{{range_type}}" }
     ]
    },
    {
     "title": "Eth2 Consensus Client Synced",
     "type": "stat",
     "description": "Identifies if the consensus client is synced",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "sync_eth2_synced", "legendFormat": "{{range_type}}" }
     ]
    }
   ]
  },
  { "title": "Charon", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "CHARON",
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Cluster Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "(\n  sum(app_git_commit) by (git_hash)\n)\n   + on(job) group_left(version)\n(\n   0 * sum(app_version) by (version)\n)\n   + on(job) group_left(lock_hash)\n(\n   0 * sum(app_lock_hash) by (lock_hash)\n)\n   + on(job) group_left(threshold)\n(\n   0 * sum(app_threshold) by (threshold)\n)\n   + on(job) group_left(num_operators)\n(\n   0 * sum(app_num_operators) by (num_operators)\n)\n   + on(job) group_left(peer_name)\n(\n   0 * sum(app_peer_name) by (peer_name)\n)"
    }
   ]
  },
  {
   "title": "Charon Status",
   "type": "stat",
   "description": "Is charon connected to a synced beacon client and a threshold of peers?",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_monitoring_readyz" }
   ]
  },
  {
   "title": "Running Since",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "(time() - app_start_time_secs)", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Current Slot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "core_scheduler_current_slot", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Number of connected peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(p2p_ping_success)" }
   ]
  },
  {
   "title": "P2P Reachability",
   "type": "stat",
   "description": "Current libp2p reachability status of this node as detected by AutoNat.",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "p2p_reachability_status" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Host machine's memory usage",
   "gridPos": { "h": 11, "w": 9, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes - node_memory_SwapCached_bytes - node_memory_Slab_bytes - node_memory_PageTables_bytes - node_memory_VmallocUsed_bytes",
     "legendFormat": "apps"
    },
    { "expr": "node_memory_Buffers_bytes", "legendFormat": "buffers" },
    { "expr": "node_memory_Cached_bytes", "legendFormat": "cached" },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "free" },
    { "expr": "node_memory_Slab_bytes", "legendFormat": "slab" }
   ]
  },
  {
   "title": "Attestations Submitted",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_bcast_broadcast_total{duty=\"attester\"}",
     "legendFormat": "{{duty}}"
    }
   ]
  },
  {
   "title": "Peer Summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(p2p_ping_success{job=\"charon\"}) by (peer)"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(p2p_ping_latency_secs_bucket{job=\"charon\"}[30s])) by (le,peer))  * 1000"
    },
    {
     "expr": "sum(core_tracker_participation{job=\"charon\", duty=\"attester\"}) by (peer)"
    },
    {
     "expr": "sum(core_tracker_participation{job=\"charon\", duty=\"proposer\"}) by (peer)"
    },
    {
     "expr": "sum(core_tracker_participation{job=\"charon\", duty=\"randao\"}) by (peer)"
    },
    {
     "expr": "sum(p2p_ping_success{job=\"charon\"}) by (peer)"
    }
   ]
  },
  {
   "title": "Blocks Proposed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_bcast_broadcast_total{duty=\"proposer\"}"
    }
   ]
  },
  {
   "title": "Beacon Node Latency (90%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(app_eth2_latency_seconds_bucket[30s])) by (le,endpoint)) ",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Peer ping latency (90%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(p2p_ping_latency_secs_bucket[30s])) by (le,peer))  ",
     "legendFormat": "{{peer}}"
    }
   ]
  },
  {
   "title": "Number of participating peers",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(core_tracker_participation{job=\"charon\"}) by (duty)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "table",
   "description": "Total Balance of Validators and beaconcha.in links for each public key.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "core_scheduler_validator_balance_gwei / 1000000000",
     "legendFormat": "{{pubkey}}"
    }
   ]
  },
  { "title": "Validator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "TEKU",
   "type": "stat",
   "description": "A teku validator client serving as part of this distributed validator cluster",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_local_validator_count"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "validator_current_epoch" }
   ]
  },
  {
   "title": "Attestations Published",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "validator_beacon_node_published_attestation_total"
    }
   ]
  },
  {
   "title": "Blocks Proposed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "validator_beacon_node_published_block_total"
    }
   ]
  },
  {
   "title": "Validator Statuses",
   "type": "table",
   "description": "Number of Validators with the given status.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "validator_local_validator_counts > 0",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Duties Failed",
   "type": "timeseries",
   "description": "Counters of each duty failed  by this cluster, separated by duty type",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "increase(validator_duties_performed{result=\"failed\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}