---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: $NAMESPACE
data:
  prometheus.yaml: |
    global:
      scrape_interval:     30s # Set the scrape interval to every 30 seconds.
      evaluation_interval: 30s # Evaluate rules every 30 seconds.
    remote_write:
      - url: https://vm.monitoring.gcp.obol.tech/write
        authorization:
          credentials: $PROM_REMOTE_WRITE_TOKEN
    scrape_configs:
      - job_name: 'charon'
        static_configs:
          - targets: ['charon:3620']
      - job_name: 'teku'
        static_configs:
          - targets: ['teku:8008']   
