---
apiVersion: v1
kind: ConfigMap
metadata:
  name: charon
  namespace: $NAMESPACE
data:
  CHARON_VALIDATOR_API_ADDRESS: "0.0.0.0:3600"
  CHARON_P2P_TCP_ADDRESS: "0.0.0.0:3610"
  CHARON_MONITORING_ADDRESS: "0.0.0.0:3620"
  CHARON_P2P_UDP_ADDRESS: "0.0.0.0:3630"
  CHARON_BEACON_NODE_ENDPOINTS: $BEACON_NODE_ENDPOINTS
  CHARON_PRIVATE_KEY_FILE: "/charon/charon/private-key"
  CHARON_LOCK_FILE: "/charon/cluster-lock.json"
  CHARON_P2P_EXTERNAL_HOSTNAME: ""
  CHARON_LOG_LEVEL: "debug"
  CHARON_LOKI_ADDRESSES: $LOKI_ADDRESSES
  CHARON_LOKI_SERVICE: "charon"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: charon
  name: charon
  namespace: $NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: charon
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: charon
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
        - name: charon
          image: ghcr.io/obolnetwork/charon:$CHARON_VERSION
          imagePullPolicy: Always
          command: ["/usr/local/bin/charon"]
          args: ["run"]
          readinessProbe:
            httpGet:
              path: /metrics
              port: 3620
            initialDelaySeconds: 5
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /metrics
              port: 3620
            initialDelaySeconds: 10
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: charon
          volumeMounts:
            - name: private-key
              mountPath: /charon/charon
            - name: cluster-lock
              mountPath: /charon
      volumes:
        - name: private-key
          projected:
            sources:
            - secret:
                name: private-key
        - name: cluster-lock
          projected:
            sources:
            - secret:
                name: cluster-lock
---
apiVersion: v1
kind: Service
metadata:
  name: charon
  namespace: $NAMESPACE
  labels:
    app: charon
spec:
  selector:
    app: charon
  ports:
    - name: validator-api
      protocol: TCP
      port: 3600
      targetPort: 3600
    - name: p2p-tcp
      protocol: TCP
      port: 3610
      targetPort: 3610
    - name: monitoring
      protocol: TCP
      port: 3620
      targetPort: 3620
    - name: p2p-udp
      protocol: UDP
      port: 3630
      targetPort: 3630
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: charon
  namespace: $NAMESPACE
spec:
  selector:
    matchLabels:
      app: charon
  endpoints:
  - port: monitoring
